### ISSUE TITLE
Bug in ByteArrayToHexViaLookupPerByte

### ISSUE THREAD

**Issue by israelchen** [patridge/PerformanceStubs#2]
Second argument in Enumerable.Range(0, 255) is the count so it should really be 256 and not 255.

Running the code with ByteArrayToHexViaLookupPerByte(new byte[] { 255 })
generates an IndexOutOfRangeException (Index was outside the bounds of the array).

**Comment by patridge** [comment]
Good catch. Thanks for letting me know.
